org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.229
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07

# Mod Properties
mod_id=ccwasm
mod_name=CC:Wasm Reforged
mod_license=GPL-3.0
mod_version=1.5.0
mod_group_id=com.iung.ccwasm
mod_authors=iung, SteamAutomata
mod_description=add wasm support for computer craft
