//! spine — a CC: Tweaked wasm module (generated by `ccwasm new`).
//!
//! Build & deploy: `ccwasm build`  (or `cargo build -r --lib --target wasm32-wasip1`)
//!
//! In game:
//!   - `wasm.load_wasm("spine")`  then call the exported functions directly
//!   - `exec_wasm spine`          event-loop driver (needs the `coroutine` feature)

use std::cell::RefCell;

use aada::prelude::*;
use cc_wasm_api::{exec_format, prelude::*};
export_funcs!(init);

/// Called once when the module is loaded from Lua.
fn init() {
    println!("spine: init");
    println!("version: 3");
    TickSyncer::spawn_handle_coroutine();
    async_main().spawn();
}

async fn async_main() -> LuaResult<()> {
    let mut ts = TickSyncer::new();
    let skel = include_str!("../asset/skel");
    let atlas = include_str!("../asset/atlas.txt");
    let texture = include_bytes!("../asset/texture.png");
    let (rt, _pages) = build_rt(&skel, &atlas)?;
    let anim = rt.animates.get_index("walk").ok_or("wrong anim")?;
    let skin = rt.skins.get_index("default").ok_or("wrong skin")?;

    Ok(())
}
