//! spine — a CC: Tweaked wasm module (generated by `ccwasm new`).
//!
//! Build & deploy: `ccwasm build`  (or `cargo build -r --lib --target wasm32-wasip1`)
//!
//! In game:
//!   - `wasm.load_wasm("spine")`  then call the exported functions directly
//!   - `exec_wasm spine`          event-loop driver (needs the `coroutine` feature)

use std::{fs, io::Cursor};

use aada::prelude::*;
use cc_wasm_api::lua_api::LuaResult;
use image::{
    ColorType::{self},
    GenericImage, GenericImageView, ImageFormat, Pixel, Rgba,
};

fn main() -> LuaResult<()> {
    // let mut ts = TickSyncer::new();
    let skel = include_str!("../asset/skel");
    let atlas = include_str!("../asset/atlas.txt");
    let texture = include_bytes!("../asset/texture.png");

    let (rt, _pages) = build_rt(&skel, &atlas)?;
    let anim = rt.animates.get_index("Close_1").ok_or("wrong anim")?;
    let skin = rt.skins.get_index("default").ok_or("wrong skin")?;
    let mut config = AnimateConfig::new();

    let sampled = rt.sample(anim, &mut config, 0.2);
    let mut pose = rt.pose_from_sample(&sampled); // 可在此修改 pose（约束前骨骼操纵）
    let state = rt.constraint_state(&sampled); // 可在此覆盖约束参数
    rt.apply_constraint_state(&mut pose, &state);
    let mut payloads = rt.build_payloads(&[skin], &sampled, &mut pose);

    payloads.clip_software();

    let (min, max) = payloads.aabb().ok_or("render error")?;
    // let (width, height, half_extent, offset) = aabb.to_params();
    let (width, height) = ((max - min).x, (max - min).y);
    let (w, h) = (width as usize, height as usize);
    let (w, h) = (w * 1, h * 1);
    let mut output = image::DynamicImage::new(w as u32, h as u32, ColorType::Rgba8);

    let texture = image::load_from_memory_with_format(texture, ImageFormat::Png)?;
    let texture = &|u: f32, v: f32| -> [f32; 4] {
        let (tex_w, tex_h) = (texture.width(), texture.height());
        let x = ((u.clamp(0.0, 1.0) * tex_w as f32) as u32).min(tex_w - 1);
        let y = ((v.clamp(0.0, 1.0) * tex_h as f32) as u32).min(tex_h - 1);
        let pix = texture.get_pixel(x, y);
        [
            pix.channels()[0] as f32 / 255.0,
            pix.channels()[1] as f32 / 255.0,
            pix.channels()[2] as f32 / 255.0,
            pix.channels()[3] as f32 / 255.0,
        ]
    };
    payloads.render_bitmap(
        w,
        h,
        (max - min) / 2.,
        (max + min) / 2.0,
        Some(texture),
        true,
        &mut |x: usize, y: usize, [r, g, b, a]: [f32; 4]| {
            output.put_pixel(
                x as u32,
                y as u32,
                Rgba([
                    (r * 255.0) as u8,
                    (g * 255.0) as u8,
                    (b * 255.0) as u8,
                    (a * 255.0) as u8,
                ]),
            );
        },
    );
    let mut png = Vec::new();
    output.write_to(Cursor::new(&mut png), ImageFormat::Png)?;

    fs::write("target/output.png", png).map_err(|e| format!("write output.png failed: {e}"))?;
    Ok(())
}
